export enum ResponseCodes {
  ISSUE_NODE_ASSIGNATION_SUCCESS = 'issue-node-assignation-success',
  ISSUE_AGENT_ASSIGNATION_SUCCESS = 'issue-agent-assignation-success',
  UPDATE_AGENT_SUCCESS = 'update-agent-success',
  NODE_UPDATE_SUCCESS = 'node-update-success',
  NODE_CATEGORY_UPDATE_SUCCESS = 'node-category-update-success',
  NODE_AGENT_UPDATE_SUCCESS = 'node-agent-update-success',
  NODE_DELETION_SUCCESS = 'node-deletion-success',
  NODE_AGENT_DELETION_SUCCESS = 'node-agent-deletion-success',
  ORGANIZATION_AGENT_DELETION_SUCCESS = 'organization-agent-deletion-success',
  ISSUE_STATUS_CHANGED_SUCCESS = 'issue-status-changed-success',
  USER_ASK_RESET_PASSWORD = 'user-ask-reset-password',
  USER_PASSWORD_RESET = 'user-password-reset',
  ACCEPT_INVITATION_SUCCESS = 'accept-invitation-success',
  CAN_CREATE_USER_FROM_INVITATION = 'can-create-user-from-invitation',
  ACCEPT_NEW_USER_INVITATION_SUCCESS = 'accept-new-user-invitation-success',
  INVITE_TOO_RECENT = 'invite-too-recent',
  DELETE_INVITATION_SUCCESS = 'delete-invitation-success',
  RESEND_INVITATION_SUCCESS = 'resend-invitation-success',
  REQUEST_ISSUE_SUCCESS = 'request-issue-success',
  REQUEST_ISSUE_APPROVED_SUCCESSFULLY = 'request-issue-approved-successfully',
  REQUEST_ISSUE_DISAPPROVED_SUCCESSFULLY = 'request-issue-disapproved-successfully',
  //
  CREATE_TRANSACTION_SUCCESS = 'create-transaction-success',
  USER_TYPE_CHANGE_SUCCESS = 'user-type-change-success',
  DRIVER_PREFERENCES_CHANGE_SUCCESS = 'driver-preferences-change-success',
}
