export enum ResponseCodes {
  USER_TYPE_CHANGE_SUCCESS = 'user-type-change-success',
  ACCEPT_TERMS_SUCCESS = 'accept-terms-success',
  ACCEPT_INVITATION_SUCCESS = 'accept-invitation-success',
  DRIVER_PREFERENCES_CHANGE_SUCCESS = 'driver-preferences-change-success',
  CREATE_CAR_SUCCESS = 'create-car-success',
  UPDATE_CAR_SUCCESS = 'update-car-success',
  DELETE_CAR_SUCCESS = 'delete-car-success',
  CREATE_RIDE_SUCCESS = 'create-ride-success',
  BOOK_SEAT_SUCCESS = 'book-seat-success',
  CANCEL_BOOKING_SUCCESS = 'book-booking-success',
  CANCEL_RIDE_SUCCESS = 'book-ride-success',
  START_RIDE_SUCCESS = 'start-ride-success',
  END_RIDE_SUCCESS = 'end-ride-success',
  ADD_REVIEW_SUCCESS = 'add-review-success',
  APPROVE_REVIEW_SUCCESS = 'approve-review-success',
  RESOLVE_DISPUTE_SUCCESS = 'resolve-dispute-success',
  GIVE_STAFF_ACCESS_SUCCESS = 'give-staff-access-success',
  BLOCK_USER_SUCCESS = 'block-user-success',
  UNBLOCK_USER_SUCCESS = 'unblock-user-success',
  CHANGE_PASSWORD_SUCCESS = 'change-password-success',
}
